# Generated by Django 2.1.7 on 2019-08-01 04:32

from django.db import migrations, models
import django.db.models.deletion
import ifor.models_dataset


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25, unique=True)),
                ('deskripsi', models.TextField()),
                ('default_dataset', models.BooleanField(default=False)),
                ('set_label', models.BooleanField(default=False)),
                ('file_dataset', models.FileField(upload_to='dataset/csv/', validators=[ifor.models_dataset.validate_file_extension])),
                ('separator', models.CharField(choices=[('koma', 'Koma'), ('titik_koma', 'Titik Koma'), ('tab', 'Tab'), ('enter', 'Enter')], default='koma', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IsolationForest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setTrain', models.IntegerField(default=4)),
                ('setVal', models.IntegerField(default=3)),
                ('setTest', models.IntegerField(default=3)),
                ('if_result', models.FileField(default='coba.csv', upload_to='iForest/result/')),
                ('if_model', models.FileField(default='coba.pkl', upload_to='iForest/model/')),
                ('if_cmval', models.FileField(default='coba.png', upload_to='iforest/cm/val/')),
                ('if_cmtest', models.FileField(default='coba.png', upload_to='iforest/cm/test/')),
                ('tanggal_running', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifor.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SetFitur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitur', models.TextField(blank=True, null=True)),
                ('default_fitur', models.BooleanField(default=False)),
                ('use_if', models.BooleanField(default=False)),
                ('all_fitur', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=True, max_length=255)),
                ('delete_fitur_with_null_val', models.BooleanField(choices=[(True, 'Ya'), (False, 'Tidak')], default=True, max_length=255)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifor.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='SetLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validate_label', models.BooleanField(default=False)),
                ('use_if', models.BooleanField(default=False)),
                ('kolom_label', models.CharField(max_length=10)),
                ('nilai_label_fraud', models.CharField(max_length=10)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ifor.Dataset')),
            ],
        ),
        migrations.AddField(
            model_name='isolationforest',
            name='setfitur',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ifor.SetFitur'),
        ),
        migrations.AddField(
            model_name='isolationforest',
            name='setlabel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifor.SetLabel'),
        ),
    ]
