# Generated by Django 2.1.7 on 2019-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hyperparameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_if', models.BooleanField(default=False)),
                ('default_hyperparameter', models.BooleanField(default=False)),
                ('n_tree', models.IntegerField(default=10)),
                ('sample', models.IntegerField(default=256)),
                ('kontaminasi', models.CharField(max_length=10)),
            ],
        ),
    ]
