# Generated by Django 2.1.7 on 2019-08-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifor', '0002_hyperparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolationforest',
            name='hyperparameter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='ifor.Hyperparameter'),
        ),
        migrations.AlterField(
            model_name='hyperparameter',
            name='kontaminasi',
            field=models.FloatField(default=0.01, max_length=10),
        ),
        migrations.AlterField(
            model_name='hyperparameter',
            name='n_tree',
            field=models.IntegerField(default=100),
        ),
    ]
