# Generated by Django 2.1.7 on 2019-08-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifor', '0003_auto_20190801_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='isolationforest',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hyperparameter',
            name='kontaminasi',
            field=models.FloatField(default=0.001, max_length=10),
        ),
    ]
